enable linux

diff --git a/.github/workflows/R.yml b/.github/workflows/R.yml
--- a/.github/workflows/R.yml
+++ b/.github/workflows/R.yml
@@ -40,50 +40,190 @@ env:
   GH_TOKEN: ${{ secrets.GH_TOKEN }}
 
 jobs:
+  rstats-linux:
+    name: R Package Linux
+    runs-on: ubuntu-20.04
+    env:
+      LIBARROW_BINARY: 'false'
+      ARROW_USER_SIMD_LEVEL: 'AVX2'
+
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
+      - uses: actions/setup-python@v4
+        with:
+          python-version: '3.7'
+
+      - uses: r-lib/actions/setup-r@v2
+        with:
+          r-version: 'devel'
+
+      - name: Install
+        env:
+          GITHUB_PAT: ${{ github.token }}
+        shell: bash
+        run: |
+          sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build texlive-latex-base texlive-fonts-extra libcurl4-openssl-dev valgrind pandoc tidy
+          mkdir -p $HOME/.R
+          R -f tools/rpkg/dependencies.R
+
+      - name: Prepare
+        shell: bash
+        run: |
+          mkdir -p /tmp/duckdb_extensions
+          cd tools/rpkg
+          ./configure
+          R CMD build .
+
+      - name: Tests
+        shell: bash
+        run: |
+          ls /tmp/duckdb_extensions
+          cd tools/rpkg
+          R CMD INSTALL -d duckdb_*.tar.gz
+          (cd tests && R -f testthat.R)
+
+      - name: R CMD check
+        shell: bash
+        run: |
+          cd tools/rpkg
+          _R_CHECK_CRAN_INCOMING_=FALSE _R_CHECK_PKG_SIZES_=FALSE R CMD check --as-cran -o /tmp duckdb_*.tar.gz
+          if egrep 'NOTE|WARNING|ERROR' /tmp/duckdb.Rcheck/00check.log ; then exit 1; fi
+
+      - name: Print R log (1)
+        # Print logs now only if success, for the case of failure there's another identical step below.
+        if: ${{ success() }}
+        shell: bash
+        run: |
+          cat /tmp/duckdb.Rcheck/00check.log
+          find /tmp/duckdb.Rcheck/ -type f -name "*.Rout*" -print0 | tee /dev/stderr | xargs -0 cat
+
+      - name: Valgrind
+        shell: bash
+        run: |
+          cd tools/rpkg
+          export NOT_CRAN='false'
+          _R_CHECK_CRAN_INCOMING_=FALSE _R_CHECK_PKG_SIZES_=FALSE R CMD check --use-valgrind -o /tmp duckdb_*.tar.gz
+
+      - name: Print check directory tree
+        if: ${{ always() }}
+        shell: bash
+        run: |
+          ls -R /tmp/duckdb.Rcheck
+
+      - name: Print R log (2)
+        if: ${{ always() }}
+        shell: bash
+        run: |
+          cat /tmp/duckdb.Rcheck/00check.log
+          find /tmp/duckdb.Rcheck/ -type f -name "*.Rout*" -print0 | tee /dev/stderr | xargs -0 cat
+
+      - name: Coverage
+        env:
+          DUCKDB_R_DEBUG: 1
+        shell: Rscript {0}
+        run: |
+          pkgload::load_all("tools/rpkg")
+          cov <- covr::codecov("tools/rpkg", relative_path = ".")
+
+      - name: Deploy
+        shell: bash
+        run: python scripts/asset-upload-gha.py duckdb_r_src.tar.gz=tools/rpkg/duckdb_*.tar.gz
+
+  rstats-linux-debug:
+    name: R Package Linux debug mode
+    runs-on: ubuntu-20.04
+    needs: rstats-linux
+
+    env:
+      LIBARROW_BINARY: 'false'
+      ARROW_USER_SIMD_LEVEL: 'AVX2'
+      DUCKDB_R_DEBUG: 1
+      DUCKDB_DEBUG_MOVE: 1
+
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
+      - uses: actions/setup-python@v4
+        with:
+          python-version: '3.7'
+
+      - uses: r-lib/actions/setup-r@v2
+        with:
+          r-version: 'devel'
+
+      - name: Install
+        env:
+          GITHUB_PAT: ${{ github.token }}
+        shell: bash
+        run: |
+          sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build libcurl4-openssl-dev
+          mkdir -p $HOME/.R
+          R -f tools/rpkg/dependencies.R
+
+      - name: Setup Ccache
+        uses: hendrikmuhs/ccache-action@main
+        with:
+          key: ${{ github.job }}
+          save: ${{ github.ref == 'refs/heads/master' || github.repository != 'duckdb/duckdb' }}
+
+      - name: Build
+        shell: bash
+        run: |
+          cd tools/rpkg
+          ./configure
+          R CMD INSTALL .
+
   rstats-windows:
     name: R Package Windows
+    needs: rstats-linux
     runs-on: windows-latest
     steps:
-    - uses: actions/checkout@v3
-      with:
-        fetch-depth: 0
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
 
-    - uses: actions/setup-python@v4
-      with:
-        python-version: '3.7'
+      - uses: actions/setup-python@v4
+        with:
+          python-version: '3.7'
 
-    - uses: r-lib/actions/setup-r@v2
-      with:
-        r-version: 'devel'
-        update-rtools: true
+      - uses: r-lib/actions/setup-r@v2
+        with:
+          r-version: 'devel'
+          update-rtools: true
 
-    - uses: r-lib/actions/setup-pandoc@v2
+      - uses: r-lib/actions/setup-pandoc@v2
 
-    - name: Setup Ccache
-      uses: hendrikmuhs/ccache-action@main
-      with:
-        key: ${{ github.job }}
-        save: ${{ github.ref == 'refs/heads/master' || github.repository != 'duckdb/duckdb' }}
+      - name: Setup Ccache
+        uses: hendrikmuhs/ccache-action@main
+        with:
+          key: ${{ github.job }}
+          save: ${{ github.ref == 'refs/heads/master' || github.repository != 'duckdb/duckdb' }}
 
-    - name: Install
-      shell: bash
-      run: |
-        R -f tools/rpkg/dependencies.R
+      - name: Install
+        shell: bash
+        run: |
+          R -f tools/rpkg/dependencies.R
 
-    - name: Build
-      shell: bash
-      run: |
-        cd tools/rpkg
-        ./configure
-        R CMD build .
-        R CMD INSTALL duckdb_*.tar.gz
-        (cd tests && R -f testthat.R)
-        _R_CHECK_CRAN_INCOMING_=FALSE _R_CHECK_PKG_SIZES_=FALSE R CMD check --as-cran --no-manual -o /tmp duckdb_*.tar.gz
-        if egrep 'NOTE|WARNING|ERROR' /tmp/duckdb.Rcheck/00check.log ; then exit 1; fi
+      - name: Build
+        shell: bash
+        run: |
+          cd tools/rpkg
+          ./configure
+          R CMD build .
+          R CMD INSTALL duckdb_*.tar.gz
+          (cd tests && R -f testthat.R)
+          _R_CHECK_CRAN_INCOMING_=FALSE _R_CHECK_PKG_SIZES_=FALSE R CMD check --as-cran --no-manual -o /tmp duckdb_*.tar.gz
+          if egrep 'NOTE|WARNING|ERROR' /tmp/duckdb.Rcheck/00check.log ; then exit 1; fi
 
   rstats-windows-extensions:
     name: R Package Windows (Extensions)
     if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
+    needs: rstats-linux
     runs-on: windows-latest
     steps:
       - uses: actions/checkout@v3
